MAX_LENGTH_USER_NAME = 150
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_TAG_SLUG = 32
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_MEASUREMENT_UNIT = 64
MAX_LENGTH_RECIPE_NAME = 256
MAX_LENGTH_SHORT_LINK = 250
LIMIT_TEXT = 20