# Generated by Django 4.2.18 on 2025-02-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'default_related_name': 'recipe_ingredients', 'verbose_name': 'Продукт в рецепте', 'verbose_name_plural': 'продукты в рецепте'},
        ),
    ]
