# Generated by Django 4.2.18 on 2025-02-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
